all:
	gcc ./check_endinness.c -o check_endinness.bin
	gcc ./shift_divisions.c -o shift_divisions.bin
	gcc ./swap_16_32_64_bit_numbers.c -o swap_16_32_64_bit_numbers.bin
	gcc ./member_size.c -o member_size.bin
clean:
	rm *.bin
